/**
 * Bundle the Bot's PURE planner core (Bot/src/lib/planner/server.ts) into a
 * self-contained CommonJS module the Strategist can require under Node.
 *
 * The planner references Screeps constants (STRUCTURE_*, TERRAIN_MASK_*) that
 * exist as globals only inside the game runtime. We inline them at build time via
 * esbuild `define`, so the emitted bundle has NO external global dependency — it
 * runs in plain Node. This is the same constant set the Bot's planner smoke uses.
 *
 * Output: vendor/planner.js  (+ the hand-maintained vendor/planner.d.ts declares
 * the surface for tsc). Regenerated by the build:planner npm script, which the
 * pre{build,test,dev,start} hooks run — so the bundle is always fresh and need
 * not be committed (it's in .gitignore).
 */
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const entry = join(here, '..', '..', 'Bot', 'src', 'lib', 'planner', 'server.ts');
const outfile = join(here, '..', 'vendor', 'planner.js');

// Screeps constants the pure planner reads as VALUES (everything else it
// references — Game/FIND_*/PathFinder/RawMemory — lives only in Room-coupled
// code that is unreachable from server.ts and gets tree-shaken away).
const STRUCT = {
  SPAWN: 'spawn',
  EXTENSION: 'extension',
  TOWER: 'tower',
  CONTAINER: 'container',
  STORAGE: 'storage',
  LINK: 'link',
  TERMINAL: 'terminal',
  LAB: 'lab',
  FACTORY: 'factory',
  POWER_SPAWN: 'powerSpawn',
  NUKER: 'nuker',
  OBSERVER: 'observer',
  ROAD: 'road',
  RAMPART: 'rampart',
  EXTRACTOR: 'extractor',
  CONSTRUCTED_WALL: 'constructedWall',
};

const define = {
  TERRAIN_MASK_WALL: '1',
  TERRAIN_MASK_SWAMP: '2',
};
for (const [k, v] of Object.entries(STRUCT)) define[`STRUCTURE_${k}`] = JSON.stringify(v);

await build({
  entryPoints: [entry],
  outfile,
  bundle: true,
  format: 'cjs',
  platform: 'node',
  target: 'node18',
  define,
  logLevel: 'info',
});

console.log(`[build-planner] bundled ${entry} -> ${outfile}`);
